# Generated by Django 3.2.4 on 2021-06-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210617_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fule_type',
            new_name='fuel_type',
        ),
    ]
